# Terraform ci cd pipeline
# This pipeline will run terraform plan and apply
# on the main branch
# when a pull request is opened, it will run terraform plan
# on the pull request branch
# when a pull request is merged, it will run terraform apply
# on the main branch

name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Terraform Apply
        if: github.event_name == 'pull_request'
        run: terraform apply -auto-approve
